
# apiversion: v1
# kind: Service
# metadata:
# 	name: nginx
# 	labels:
# 		run: ngynx
# spec:
# 	ports:
# 	-	port: 80
# 		protocol: TCP
# 	selector:
# 		run: nginx
# 	-	port: 443
# 		protocol: TCP
# 		targetPort: 443
# 	-	port: 22
# 		protocol: TCP
# 		targetPort: 22

# ---

# apiversion: apps/v1
# kind: Deployment
# metadata:
# 	name: nginx-deployment
# spec:
# 	replicas: 1
# 	template: 
# 		metadata:
# 			labels:
# 				app: nginx
# 	spec:
# 		containers:
# 		- name: nginx
# 		  image: my_nginx
# 		  imagePullPolicy: Never
# 		  ports:
# 			- containerPort: 80

apiVersion: app/v1
kind: Deployment
metadata:
	name: nginx
spec:
	selector:
		matchLabels:
			run: nginx
	replicas: 2
	template:
		metadata:
			labels:
				run: nginx
	spec:
		containers:
			- name: nginx
			image: my_nginx
			imagePullPolicy: Never
			ports:
				- containerPort: 80
